<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="188" started-at="2015-03-31T00:28:56Z" finished-at="2015-03-31T00:28:56Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="188" started-at="2015-03-31T00:28:56Z" finished-at="2015-03-31T00:28:56Z">
      <class name="com.booj.base.FactoryTest">
        <test-method status="FAIL" signature="setupBeforeTestMethod()[pri:0, instance:com.booj.base.FactoryTest@2c6a3f77]" name="setupBeforeTestMethod" is-config="true" duration-ms="0" started-at="2015-03-30T18:28:56Z" finished-at="2015-03-30T18:28:56Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.booj.base.BaseSuperFactory.setupBeforeTestMethod(BaseSuperFactory.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:653)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupBeforeTestMethod -->
        <test-method status="SKIP" signature="tearDownAfterTestMethod()[pri:0, instance:com.booj.base.FactoryTest@2c6a3f77]" name="tearDownAfterTestMethod" is-config="true" duration-ms="0" started-at="2015-03-30T18:28:56Z" finished-at="2015-03-30T18:28:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterTestMethod -->
        <test-method status="SKIP" signature="test_Login_Button_Present_Pass()[pri:0, instance:com.booj.base.FactoryTest@2c6a3f77]" name="test_Login_Button_Present_Pass" duration-ms="0" started-at="2015-03-30T18:28:56Z" finished-at="2015-03-30T18:28:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Login_Button_Present_Pass -->
      </class> <!-- com.booj.base.FactoryTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
